import type { StrapiApp } from '@strapi/strapi/admin';

export const ptBRTranslations: Record<string, string> = {
  'app.components.LeftMenu.navbrand.title': 'Valhalla',
  'app.components.LeftMenu.navbrand.workplace': 'Painel da loja',
  'global.home': 'Início',
  'content-manager.plugin.name': 'Gerenciador de Conteúdo',
  'widget.deploy-now.title': 'Implantar',
  'HomePage.widget.deploy-now.title': 'Pronto para publicar?',
  'cloud.Plugin.name': 'Implantar',
  'search.placeholder': 'Pesquisar',
  'content-manager.containers.list.table-headers.status': 'Status',
  'content-manager.containers.edit.header.more-actions': 'Mais ações',
  'content-manager.containers.edit.panels.default.more-actions': 'Mais ações do documento',
  'content-manager.dnd.instructions': 'Pressione a barra de espaço para selecionar e reordenar',
  'content-manager.containers.edit.panels.default.title': 'Registro',
  'content-manager.containers.edit.title.new': 'Criar um registro',
  'content-manager.containers.edit.tabs.draft': 'Rascunho',
  'content-manager.containers.edit.tabs.published': 'Publicado',
  'content-manager.containers.edit.information.last-published.label': 'Publicado',
  'content-manager.containers.List.draft': 'Rascunho',
  'content-manager.containers.List.published': 'Publicado',
  'app.utils.published': 'Publicado',
  'app.HeaderLayout.docLink.label': 'Saiba mais na documentação',
  'Settings.profile.form.section.experience.interfaceLanguageHelp':
    'As alterações de preferência se aplicam apenas a você. Mais informações estão disponíveis {here}.',
  'Settings.profile.form.section.experience.mode.option-system-label':
    'Usar configurações do sistema',
  'tours.profile.title': 'Tour guiado',
  'tours.profile.description': 'Você pode reiniciar o tour guiado a qualquer momento.',
  'tours.profile.reset': 'Reiniciar tour guiado',
  'tours.profile.notification.success.reset': 'Tour guiado reiniciado',
  'content-manager.widget.last-published.title': 'Últimos registros publicados',
  'content-manager.widget.last-published.no-data': 'Nenhum registro publicado',
  'HomePage.widget.deploy-now.description': 'Implantar com o Strapi Cloud',
  'HomePage.widget.deploy-now.button': 'Implantar agora',
  'list.asset.at.finished': 'Mídias terminaram de carregar.',
  Produto: 'Produto',
  Categoria: 'Categoria',
  Etiqueta: 'Etiqueta',
  Marca: 'Marca',
  'Pergunta Frequente': 'Pergunta Frequente',
  Política: 'Política',
  User: 'Usuário',
  'Configurações do Site': 'Configurações do Site',
  'Página Inicial': 'Página Inicial',
  'content-manager.content-types.api::product.product.mainImage': 'Imagem principal',
  'content-manager.content-types.api::product.product.name': 'Nome do produto',
  'content-manager.content-types.api::product.product.basePrice': 'Preço base (R$)',
  'content-manager.content-types.api::product.product.category': 'Categoria',
  'content-manager.content-types.api::product.product.brand': 'Marca',
  'content-manager.content-types.api::product.product.tags': 'Etiquetas',
  'content-manager.content-types.api::product.product.variantGroupLabel':
    'Título do grupo de variações',
  'content-manager.content-types.api::product.product.specs': 'Especificações',
  'content-manager.content-types.api::product.product.description': 'Descrição',
  'content-manager.content-types.api::product.product.warranty': 'Garantia',
  'content-manager.content-types.api::product.product.gallery': 'Galeria de imagens',
  'content-manager.content-types.api::product.product.seo': 'SEO (opcional)',
  'content-manager.content-types.api::product.product.variants': 'Variações',
  'content-manager.components.shared.seo.metaTitle': 'Título (SEO)',
  'content-manager.components.shared.seo.metaDescription': 'Descrição (SEO)',
  'content-manager.components.shared.seo.shareImage': 'Imagem de compartilhamento',
  'content-manager.components.ecommerce.variant.sku': 'Código (SKU)',
  'content-manager.components.ecommerce.variant.colorName': 'Nome da cor',
  'content-manager.components.ecommerce.variant.colorHex': 'Cor',
  'content-manager.components.ecommerce.variant.configLabel': 'Configuração',
  'content-manager.components.ecommerce.variant.price': 'Preço (R$)',
  'content-manager.components.ecommerce.variant.compareAtPrice': "Preço 'De' (R$)",
  'content-manager.components.ecommerce.variant.available': 'Disponível',
  'content-manager.components.ecommerce.variant.stockQuantity': 'Estoque',
  'content-manager.components.ecommerce.variant.image': 'Imagem da variação',
  'components.Blocks.blocks.bulletList': 'Lista com marcadores',
  'components.Blocks.blocks.numberList': 'Lista numerada',
};

export default {
  config: {
    locales: ['pt-BR'],
    translations: {
      'pt-BR': ptBRTranslations,
    },
  },
  bootstrap(_app: StrapiApp) {},
};
